enableGlobalCache: false

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: "http://npm.dev.wixpress.com/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: "https://yarn.build/latest/build"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"
    
supportedArchitectures:
  cpu:
    - arm64
    - x86
  os:
    - linux
    - darwin

unsafeHttpWhitelist:
  - npm.dev.wixpress.com

yarnPath: .yarn/releases/yarn-3.4.1.cjs
